"""Sanitize clean Feniks days to match the measurement contract."""

import aiosqlite


async def up(db: aiosqlite.Connection) -> None:
    # A clean day may keep a note about a shorter exposure, but watched-only
    # measurements must not remain hidden behind a clean outcome. Preserve old
    # values in the one field the new clean-day contract keeps visible.
    await db.execute(
        """UPDATE feniks_daily
           SET note = '[legacy clean measurement: ' ||
                COALESCE(CAST(minutes AS TEXT) || ' min', 'minutes not recorded') ||
                CASE WHEN edging = 1 THEN '; edging yes' ELSE '' END || '] ' ||
                COALESCE(note, '')
           WHERE used = 0 AND (minutes IS NOT NULL OR edging = 1)"""
    )

    # Rows below the new watched threshold are exposures, not watched outcomes.
    # Keep the original values and remove only relapse events generated by the
    # daily-log flow; independently recorded relapse history remains untouched.
    await db.execute(
        """UPDATE feniks_daily
           SET note = '[legacy watched outcome below 5-minute contract: ' ||
                COALESCE(CAST(minutes AS TEXT) || ' min', 'minutes not recorded') ||
                CASE WHEN edging = 1 THEN '; edging yes' ELSE '' END || '] ' ||
                COALESCE(note, '')
           WHERE used = 1 AND COALESCE(minutes, 0) < 5"""
    )
    await db.execute(
        """DELETE FROM pmo_events
           WHERE event_type = 'relapse' AND notes = 'via daily log'
             AND date IN (SELECT date FROM feniks_daily WHERE used = 1 AND COALESCE(minutes, 0) < 5)"""
    )
    await db.execute(
        "UPDATE feniks_daily SET used = 0, minutes = NULL, edging = 0 WHERE used = 1 AND COALESCE(minutes, 0) < 5"
    )
    await db.execute("UPDATE feniks_daily SET minutes = NULL, edging = 0 WHERE used = 0")
