"""Predefined exercise library for the Training module.

Users can pick from the library (prefills name/sets/reps/notes) or type
a custom exercise — the library is a convenience, not a constraint.
Sections match training SECTION_ORDER: Warmup / Core / Cardio / Stretching.
"""

EXERCISE_LIBRARY: list[dict] = [
    # ── Workout A (kettlebell full-body) ─────────────────────────────
    {
        "category": "Workout A (KB full-body)",
        "section": "Core",
        "name": "Goblet Squat",
        "sets": 4,
        "reps": "10-12",
        "notes": "KB at chest, full depth, torso upright, knees out",
    },
    {
        "category": "Workout A (KB full-body)",
        "section": "Core",
        "name": "Push-up on KB",
        "sets": 4,
        "reps": "10-12",
        "notes": "Hands on KB handles, chest below hands, shoulder blades packed",
    },
    {
        "category": "Workout A (KB full-body)",
        "section": "Core",
        "name": "Bent-over Row",
        "sets": 4,
        "reps": "10-12",
        "notes": "Torso ~45°, flat back, pull to belly, 1s pause at top",
    },
    {
        "category": "Workout A (KB full-body)",
        "section": "Core",
        "name": "Seated KB Press",
        "sets": 3,
        "reps": "8-10/side",
        "notes": "Seated (low ceiling), press to full lockout",
    },
    {
        "category": "Workout A (KB full-body)",
        "section": "Core",
        "name": "Farmer's Walk",
        "sets": 3,
        "reps": "30-45s",
        "notes": "Tall posture, shoulders down and back",
    },
    {
        "category": "Workout A (KB full-body)",
        "section": "Core",
        "name": "Plank",
        "sets": 3,
        "reps": "45s",
        "notes": "Glutes and abs tight, straight line, no hip sag",
    },
    # ── Workout B (kettlebell full-body) ─────────────────────────────
    {
        "category": "Workout B (KB full-body)",
        "section": "Core",
        "name": "Romanian Deadlift",
        "sets": 4,
        "reps": "10-12",
        "notes": "Hips BACK, flat back, KB slides along legs — hinge, not squat",
    },
    {
        "category": "Workout B (KB full-body)",
        "section": "Core",
        "name": "Pull-up",
        "sets": 4,
        "reps": "max",
        "notes": "Chin over bar; scale: band or 5s negatives",
    },
    {
        "category": "Workout B (KB full-body)",
        "section": "Core",
        "name": "Floor Press",
        "sets": 3,
        "reps": "10/side",
        "notes": "Lying on floor, press KB to lockout, elbow back to floor",
    },
    {
        "category": "Workout B (KB full-body)",
        "section": "Core",
        "name": "Single-arm Row",
        "sets": 3,
        "reps": "10-12/side",
        "notes": "Hand+knee supported, full stretch at bottom",
    },
    {
        "category": "Workout B (KB full-body)",
        "section": "Core",
        "name": "KB Swing",
        "sets": 3,
        "reps": "15",
        "notes": "Hip snap drives the bell — arms are ropes. Master RDL first",
    },
    {
        "category": "Workout B (KB full-body)",
        "section": "Core",
        "name": "Dead Bug",
        "sets": 3,
        "reps": "8/side",
        "notes": "Slow opposite arm+leg, lower back GLUED to floor",
    },
    # ── Kettlebell — more ────────────────────────────────────────────
    {
        "category": "Kettlebell",
        "section": "Core",
        "name": "KB Clean",
        "sets": 3,
        "reps": "8/side",
        "notes": "Hip drive, soft catch in rack position",
    },
    {
        "category": "Kettlebell",
        "section": "Core",
        "name": "KB Lunge",
        "sets": 3,
        "reps": "8-10/side",
        "notes": "Goblet or racked, knee tracks over toes",
    },
    {
        "category": "Kettlebell",
        "section": "Core",
        "name": "Turkish Get-up",
        "sets": 3,
        "reps": "3/side",
        "notes": "Slow and controlled, eyes on the bell",
    },
    {
        "category": "Kettlebell",
        "section": "Core",
        "name": "Renegade Row",
        "sets": 3,
        "reps": "8/side",
        "notes": "Plank + row, hips stay square",
    },
    {
        "category": "Kettlebell",
        "section": "Core",
        "name": "KB Halo",
        "sets": 3,
        "reps": "8/side",
        "notes": "Circle the head, ribs down, slow",
    },
    # ── Bodyweight ───────────────────────────────────────────────────
    {
        "category": "Bodyweight",
        "section": "Core",
        "name": "Push-up",
        "sets": 4,
        "reps": "max",
        "notes": "Body as one plank, full range",
    },
    {
        "category": "Bodyweight",
        "section": "Core",
        "name": "Diamond Push-up",
        "sets": 3,
        "reps": "max",
        "notes": "Elbows close — triceps finisher",
    },
    {
        "category": "Bodyweight",
        "section": "Core",
        "name": "Dip (chairs/bars)",
        "sets": 3,
        "reps": "max",
        "notes": "Shoulders down, controlled depth",
    },
    {
        "category": "Bodyweight",
        "section": "Core",
        "name": "Hanging Knee Raise",
        "sets": 3,
        "reps": "12-15",
        "notes": "No swinging, control down",
    },
    {
        "category": "Bodyweight",
        "section": "Core",
        "name": "Side Plank",
        "sets": 3,
        "reps": "30s/side",
        "notes": "Straight line, hips high",
    },
    {
        "category": "Bodyweight",
        "section": "Core",
        "name": "Pallof Press (band)",
        "sets": 3,
        "reps": "10/side",
        "notes": "Anti-rotation — resist the twist",
    },
    # ── Gym classics (barbell/machines) ──────────────────────────────
    {
        "category": "Gym classics",
        "section": "Core",
        "name": "Back Squat",
        "sets": 4,
        "reps": "6-10",
        "notes": "Barbell, full depth, brace hard",
    },
    {
        "category": "Gym classics",
        "section": "Core",
        "name": "Deadlift",
        "sets": 3,
        "reps": "5-8",
        "notes": "Flat back, bar close, hinge",
    },
    {
        "category": "Gym classics",
        "section": "Core",
        "name": "Bench Press",
        "sets": 4,
        "reps": "6-10",
        "notes": "Shoulder blades pinned, feet planted",
    },
    {
        "category": "Gym classics",
        "section": "Core",
        "name": "Overhead Press",
        "sets": 3,
        "reps": "6-10",
        "notes": "Glutes tight, no lean-back",
    },
    {
        "category": "Gym classics",
        "section": "Core",
        "name": "Barbell Row",
        "sets": 4,
        "reps": "8-12",
        "notes": "Torso ~45°, pull to lower chest",
    },
    {
        "category": "Gym classics",
        "section": "Core",
        "name": "Lat Pulldown",
        "sets": 3,
        "reps": "10-12",
        "notes": "Elbows to hips, no swinging",
    },
    {
        "category": "Gym classics",
        "section": "Core",
        "name": "Biceps Curl",
        "sets": 3,
        "reps": "10-15",
        "notes": "No body swing, full range",
    },
    {
        "category": "Gym classics",
        "section": "Core",
        "name": "Triceps Extension",
        "sets": 3,
        "reps": "10-15",
        "notes": "Elbows still, slow eccentric",
    },
    # ── Warmup / Mobility ────────────────────────────────────────────
    {
        "category": "Warmup",
        "section": "Warmup",
        "name": "Band Pull-apart",
        "sets": 2,
        "reps": "15",
        "notes": "Wakes upper back — arms straight, band to chest",
    },
    {
        "category": "Warmup",
        "section": "Warmup",
        "name": "Thoracic Extension (roller)",
        "sets": 1,
        "reps": "90s",
        "notes": "Roller at shoulder blades, extend over it",
    },
    {
        "category": "Warmup",
        "section": "Warmup",
        "name": "Goblet Hold (deep squat)",
        "sets": 2,
        "reps": "30s",
        "notes": "Elbows push knees out — opens hips",
    },
    {
        "category": "Warmup",
        "section": "Warmup",
        "name": "Band Dislocates",
        "sets": 2,
        "reps": "10",
        "notes": "Wide grip, slow over the head",
    },
    {
        "category": "Warmup",
        "section": "Warmup",
        "name": "Jumping Jacks",
        "sets": 2,
        "reps": "30s",
        "notes": "Raise the pulse gently",
    },
    # ── Cardio ───────────────────────────────────────────────────────
    {
        "category": "Cardio",
        "section": "Cardio",
        "name": "Boxing Bag Rounds",
        "sets": 3,
        "reps": "2 min",
        "notes": "Jab-cross, stay on toes",
    },
    {
        "category": "Cardio",
        "section": "Cardio",
        "name": "KB Swing Intervals",
        "sets": 5,
        "reps": "20 + rest",
        "notes": "Power endurance — hips!",
    },
    {
        "category": "Cardio",
        "section": "Cardio",
        "name": "Jump Rope",
        "sets": 3,
        "reps": "2 min",
        "notes": "Light on feet",
    },
    {
        "category": "Cardio",
        "section": "Cardio",
        "name": "Zone 2 Walk (dog)",
        "sets": 1,
        "reps": "60 min",
        "notes": "Conversational pace",
    },
    {
        "category": "Cardio",
        "section": "Cardio",
        "name": "Swimming",
        "sets": 1,
        "reps": "45-60 min",
        "notes": "Easy technique focus",
    },
    # ── Stretching / Cooldown ────────────────────────────────────────
    {
        "category": "Stretching",
        "section": "Stretching",
        "name": "Hamstring Stretch",
        "sets": 2,
        "reps": "30s/side",
        "notes": "Hinge, flat back, breathe",
    },
    {
        "category": "Stretching",
        "section": "Stretching",
        "name": "Hip Flexor Stretch",
        "sets": 2,
        "reps": "30s/side",
        "notes": "Half-kneel, glute tight, tall chest",
    },
    {
        "category": "Stretching",
        "section": "Stretching",
        "name": "Couch Stretch",
        "sets": 2,
        "reps": "30s/side",
        "notes": "Rear foot elevated, ease into it",
    },
    {
        "category": "Stretching",
        "section": "Stretching",
        "name": "Child's Pose",
        "sets": 1,
        "reps": "60s",
        "notes": "Long spine, slow breath",
    },
    {
        "category": "Stretching",
        "section": "Stretching",
        "name": "Box Breathing",
        "sets": 1,
        "reps": "3 min",
        "notes": "4s in — 4s hold — 4s out — 4s hold",
    },
]
